# Permissions necessary to use the Azure/login action.
# Even if you grant read/write at the repo level, you still need id-token.
permissions:
  contents: read
  pages: write
  id-token: write

name: DEV - Score Model

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - dev
    paths:
      - Pipeline/data/**
      - Pipeline/deploy-score.py
      - .github/workflows/score_model_dev.yml

jobs:
  deploy_ml_scoring_pipeline:
    name: DEV - Deploy the Scoring pipeline to Azure ML
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - name: Repo checkout
      uses: actions/checkout@v3
    - name: Print GitHub OIDC subject
      run: |
        echo "Subject: repo:${{ github.repository }}:environment:${{ github.ref_name }}"  
    - name: Install az CLI
      run: |
        # Install the az CLI and ML extension
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az extension add -n ml -y
        echo "Installed Azure CLI and ML extension"
    ###############################################################
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    ################################################################
    - name: Install and prepare Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Run AML pipeline
      run: |
        cd Pipeline/
        echo "Installing dependencies"
        python -m pip install -r requirements.txt
        echo "Creating config file"
        mkdir .azureml
        echo -e "{ \"subscription_id\": \"${{ secrets.AZURE_SUBSCRIPTION_ID }}\", \"resource_group\": \"leonardobarrera.s-rg\", \"workspace_name\": \"Leogithubactions\" }" > .azureml/config.json
        echo "Run scoring pipeline"
        # Run scoring pipeline
        python deploy-score.py